<project xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ru.reinform.rinrif.manager-tools</groupId>
    <artifactId>manager-tools-root</artifactId>
    <version>internal</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>ru.reinform.cdp.maven-master</groupId>
        <artifactId>root-master</artifactId>
        <version>5.0</version>
    </parent>

    <profiles>
        <profile>
            <id>target-server</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <modules>
                <module>model</module>
                <module>core</module>
                <module>atr2spec</module>
                <module>server</module>
            </modules>
        </profile>
        <profile>
            <id>target-remote-api</id>
            <modules>
                <module>model</module>
                <module>remote-api</module>
            </modules>
        </profile>
    </profiles>
</project>
